stages:
  - build
  - test
  - process

variables:
  URL: $URL

compile:
  stage: build
  script:
    - pwd
    - which python
    - mkdir build
    - cd build
    - cmake
      -Dwith_pybind11=ON
      -Dwith_cppad=ON
      -Dwith_tests=ON
      -Dwith_python=ON
      -Dwith_gurobi=ON
      -DGUROBI_LIBRARY=$GUROBI_LIBRARY/libgurobi95.so
      -DGUROBI_INCLUDE_DIRS=$GUROBI_INCLUDE_DIRS
      -DGUROBI_CXX_LIBRARY=$GUROBI_LIBRARY/libgurobi_g++5.2.a
      -DPYTHON_EXECUTABLE=$PYTHON_EXECUTABLE
      -Dwith_compact=OFF
      -Dwith_docs=OFF ..
    - make install_tpls
    - make install
  artifacts:
    paths:
      - build
    expire_in: 1 hour

unit-tests:
  stage: test
  script:
    - pwd
    - cd build
    - ls
    - make test
  allow_failure: true

performance-tests:
  stage: test
  script:
    - cd build
    - make coek_solve0
    - make coek_writer
    - make gurobi_solve0
    - make gurobi_writer
    - cd ../test/aml_comparisons/
    - mkdir build
    - cd build
    - ../scripts/run bench_coek 1
    - ../scripts/collect
    - ../scripts/dog solve0
    - ../scripts/dog writer
    - python ../scripts/to_csv.py
  artifacts:
    paths:
      - test/aml_comparisons/build/results/solve0/solve0_summary.csv
      - test/aml_comparisons/build/results/writer/writer_summary.csv
    expire_in: 30 days

combine-performance-results:
  stage: process
  script:
    - cd test/aml_comparisons/build
    #- 'curl -k --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOEKN" "${URL}download?job=performance-tests"'
    - GET /or-fusion/coek/jobs/11372303/artifacts/test/aml_comparisons/build/results/solve0/solve0_summary.csv
    - ls
  rules:
    - if: $CI_COMMIT_BRANCH == "dev-private"
