coek:
  script:
    - apt-get update
    - apt-get install -y g++ cmake gcovr git
    - git clone https://github.com/catchorg/Catch2 catch
    - cd catch
    - git checkout -b v2.4.1
    - git branch
    - cd ..
    - mkdir build
    - cd build
    - cmake -D with_tests=ON --with_gcov=ON ..
    - make
    - make test_verbose
    - make gcovr
