coek:
  script:
    - apt-get update
    - apt-get install -y g++ cmake gcovr git
    - git clone --branch v2.4.1 https://github.com/catchorg/Catch2 catch
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test_verbose
