coek:
  script:
    - apt-get update
    - apt-get install -y g++ cmake gcovr git
    - cd third_party
    - ./getCatch2.sh
    - cd ..
    - mkdir build
    - cd build
    - cmake -D with_tests=ON -D with_gcov=ON ..
    - make
    - make test_verbose
    - make gcovr
