coek:
  script:
    - apt-get update
    - apt-get install -y g++ cmake gcovr git
    - git clone https://github.com/catchorg/Catch2 catch
    - cd catch
    - git branch
    - git checkout v2.4.1
    - git branch
    - cd ..
    - mkdir build
    - cd build
    - cmake ..
    - make
    - make test_verbose
