stages:
  - build
  - test

build_coek:
  stage: build
  script:
    - apt-get update
    - apt-get install -y g++ cmake git
    - pwd
    - cd ..
    - ls
    - git clone https://gitlab.com/coopr/coek.git
    - cd coek
    - mkdir build
    - cd build
    - cmake -D with_tests=ON ..
    - make
    - make test_verbose
    - cd ../..

install_poek:
  stage: build
  script:
    - apt-get miniconda
    - which python
    - python --version

test_coek:
  stage: test
  script:
    - cd ../coek/build
    - make test_verbose

test_poek:
  stage: test
  script:
    - cd ../poek/poek
    - nose

