version: 2

conda:
    environment: doc/environment.yml

build:
    os: ubuntu-22.04
    tools:
        python: "mambaforge-4.10"
    commands:
        - ./doc/build_doc.sh ${SPHINX_PROJECT}

#python:
#    install:
#        - requirements: doc/requirements.txt
