version: 2

conda:
    environment: doc/environment.yml

build:
    os: ubuntu-22.04
    tools:
        python: "3.9"
    jobs:
        commands:
            - ./doc/coek_doc_setup.sh ${SPHINX_PROJECT}

#python:
#    install:
#        - requirements: doc/requirements.txt
