version: 2

conda:
    environment: doc/environment.yml

build:
    os: ubuntu-22.04
    tools:
        python: "3.9"
    commands:
        - conda env create -f environment.yml
        - ./doc/coek_doc_setup.sh ${SPHINX_PROJECT}

#python:
#    install:
#        - requirements: doc/requirements.txt
