version: 2

conda:
    environment: doc/environment.yml

build:
    os: ubuntu-22.04
    tools:
        python: "3.9"
    jobs:
        pre_build:
            - ./doc/coek_doc_setup.sh ${SPHINX_PROJECT}

#sphinx:
#    configuration: lib/${SPHINX_PROJECT}/doc/conf.py

#python:
#    install:
#        - requirements: doc/requirements.txt
