version: 2

conda:
    environment: doc/environment.yml

build:
    os: ubuntu-22.04
    tools:
        python: "mambaforge-4.10"
    commands:
        - mamba env create -f doc/environment.yml
        - conda init bash
        - ./doc/coek_doc_setup.sh ${SPHINX_PROJECT}

#python:
#    install:
#        - requirements: doc/requirements.txt
