name: Linux Build and Tests

on:
  workflow_dispatch:
  push:
    branches: [ main, dev, public ]
  pull_request:
    branches: [ main, dev, public ]

jobs:

  coek-simple-build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: run cmake
        run: |
          mkdir build
          cd build
          cmake -Dinstall_all_tpls=OFF -Dwith_python=OFF ../lib/coek
      - name: build
        run: |
          cd build
          make
          
  coek-build-and-test-with-tpls:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: run cmake
        run: |
          mkdir build
          cd build
          cmake -Dwith_python=OFF -Dwith_tests=ON ../lib/coek
      - name: build
        run: |
          cd build
          make install_tpls
          make
      - name: test
        run: |
          cd build
          make test

  pycoek_pybind11:
    runs-on: ubuntu-latest
    needs: coek-build-and-test-with-tpls
    steps:
      - uses: actions/checkout@v2
      - name: run cmake
        run: |
          mkdir build
          cd build
          cmake  ../lib/coek
      - name: build
        run: |
          cd build
          make install_tpls
          make
        
